// Core Campus Design Tokens — shared source of truth
// Used in tailwind.config.js (Vue) and injected as CSS vars in Angular

export const colors = {
  "surface": "#f7f9fb",
  "surface-dim": "#d8dadc",
  "surface-bright": "#f7f9fb",
  "surface-container-lowest": "#ffffff",
  "surface-container-low": "#f2f4f6",
  "surface-container": "#eceef0",
  "surface-container-high": "#e6e8ea",
  "surface-container-highest": "#e0e3e5",
  "on-surface": "#191c1e",
  "on-surface-variant": "#45464d",
  "inverse-surface": "#2d3133",
  "inverse-on-surface": "#eff1f3",
  "outline": "#76777d",
  "outline-variant": "#c6c6cd",
  "surface-tint": "#565e74",
  "primary": "#000000",
  "on-primary": "#ffffff",
  "primary-container": "#131b2e",
  "on-primary-container": "#7c839b",
  "inverse-primary": "#bec6e0",
  "secondary": "#0051d5",
  "on-secondary": "#ffffff",
  "secondary-container": "#316bf3",
  "on-secondary-container": "#fefcff",
  "tertiary": "#000000",
  "on-tertiary": "#ffffff",
  "tertiary-container": "#0b1c30",
  "on-tertiary-container": "#75859d",
  "error": "#ba1a1a",
  "on-error": "#ffffff",
  "error-container": "#ffdad6",
  "on-error-container": "#93000a",
  "primary-fixed": "#dae2fd",
  "primary-fixed-dim": "#bec6e0",
  "on-primary-fixed": "#131b2e",
  "on-primary-fixed-variant": "#3f465c",
  "secondary-fixed": "#dbe1ff",
  "secondary-fixed-dim": "#b4c5ff",
  "on-secondary-fixed": "#00174b",
  "on-secondary-fixed-variant": "#003ea8",
  "tertiary-fixed": "#d3e4fe",
  "tertiary-fixed-dim": "#b7c8e1",
  "on-tertiary-fixed": "#0b1c30",
  "on-tertiary-fixed-variant": "#38485d",
  "background": "#f7f9fb",
  "on-background": "#191c1e",
  "surface-variant": "#e0e3e5",
};

export const fontSize = {
  "display-lg":  ["36px", { lineHeight: "44px",  letterSpacing: "-0.02em", fontWeight: "700" }],
  "headline-md": ["24px", { lineHeight: "32px",  letterSpacing: "-0.01em", fontWeight: "600" }],
  "headline-sm": ["18px", { lineHeight: "28px",  fontWeight: "600" }],
  "body-lg":     ["16px", { lineHeight: "24px",  fontWeight: "400" }],
  "body-md":     ["14px", { lineHeight: "20px",  fontWeight: "400" }],
  "label-md":    ["12px", { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "500" }],
  "label-sm":    ["11px", { lineHeight: "14px",  fontWeight: "600" }],
};

export const borderRadius = {
  "sm":      "0.125rem",
  "DEFAULT": "0.25rem",
  "md":      "0.375rem",
  "lg":      "0.5rem",
  "xl":      "0.75rem",
  "full":    "9999px",
};

export const spacing = {
  "base":           "4px",
  "xs":             "0.5rem",
  "sm":             "1rem",
  "md":             "1.5rem",
  "lg":             "2.5rem",
  "xl":             "4rem",
  "gutter":         "1.5rem",
  "margin-mobile":  "1rem",
  "margin-desktop": "2.5rem",
};
